
spring:
  # THYMELEAF (ThymeleafAutoConfiguration) : 默认配置
  thymeleaf:
    check-template-location: true
    prefix: classpath:/views/   # 默认为 /templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: true

# 数据源配置
  # (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    name: ds-h2
    url: jdbc:h2:D:/work/workspace/fork/gs-serving-web-content/initial/data/fdata;DATABASE_TO_UPPER=false
    username: h2
    password: h2
    driver-class: org.h2.Driver

# 更多数据源
custom:
  datasource:
    names: ds1,ds2
    ds1:
      url: jdbc:mysql://localhost:3306/test1
      username: root
      password: 123456
      driver-class: com.mysql.jdbc.Driver

    ds2:
      url: jdbc:mysql://localhost:3306/test2
      username: ssm
      password: ssm
      driver-class: com.mysql.jdbc.Driver